#!/bin/sh
# AlertGizmo web-build (agwb) container build & run script
# by Ian Kluft
#
# In normal operation:
# * the container is built from Github Actions after modification to this directory .github/workflows/mk-container.yml
# * the container is launched from Github Actions after any modification to the repo .github/workflows/buildsite.yml
# To test the container:
# * build container: run this script within the web-build/container directory as "agwb-build"
# * run web build: run this script within the web-build/container directory as "agwb-run"

cmdname="$(basename "$0")"
basedir="$(dirname "$(dirname "$PWD")")"
image_name=alertgizmo-web-build
if [ "$cmdname" = "agwb-build" ]
then
    cd "$basedir" && time buildah build --userns=host --security-opt label=disable -t "$image_name" -f web-build/container/Containerfile \
        || exit 1
elif [ "$cmdname" = "agwb-run" ]
then
    time podman run --userns=keep-id --security-opt label=disable "$image_name" \
        || exit 1
else
    echo "command name $0 unexpected - use agwb-build or agwb-run" >&2
    exit 1
fi

