---
# derived from Perl Foundation's Proposed Perl Changes workflow by Dave Cross
# https://github.com/Perl/PPCs/blob/main/.github/workflows/buildsite.yml
name: Generate web site
# yamllint disable rule:line-length

on:  # yamllint disable-line rule:truthy
  push:
    branches: 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 'ikluft/web-build/container/Dockerfile@main'

    steps:
      - name: Perl version
        run: perl -v

      - name: Checkout
        uses: actions/checkout@v4

      - name: Create templated pages
        run: web-build/container/entrypoint.sh

      - name: Update pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
