---
name: Make container image
# yamllint disable rule:line-length
# build the container to house the tools so AlertGizmo web builds take minimal resources each run
# by Ian Kluft
# borrows from examples at redhat-actions/buildah-build and redhat-actions/push-to-registry/.../ghcr-push.yaml

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - 'web-build/container/**'
      - '!web-build/container/agwb-*'
      - '.github/workflows/mk-container.yml'
    branches: 'main'
  workflow_dispatch:

env:
  IMAGE_NAME: alertgizmo-web-build
  IMAGE_TAGS: agwb-v1 ${{ github.sha }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Build image using Buildah action
      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          containerfiles: |
            ./web-build/container/Containerfile
          extra-args: |
            --userns=host
            --security-opt label=disable
          oci: true
          # build-args: |
          #   some_arg=some_value

      # Push container image to Github Container Registry GHCR
      - name: Push to GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust

      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
